# Generated by Django 4.1.7 on 2023-05-14 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, upload_to='PartenairePhoto/')),
                ('Partenaire_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(choices=[('graphic design', 'graphic design'), ('Web Design', 'Web Design'), ('Vaudiovisual production', 'audiovisual production'), (' Animation 3D ', 'Animation 3D ')], default='Web Design', max_length=50)),
                ('Ser_description', models.TextField(null=True)),
                ('img', models.ImageField(blank=True, upload_to='servicesPhoto/')),
                ('tag', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('client_name', models.CharField(max_length=50, null=True)),
                ('number_client', models.CharField(max_length=50, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='photos/')),
                ('dateD', models.DateField(auto_now_add=True)),
                ('dateF', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('In progress', 'In progress'), ('Reviewing', 'Reviewing'), ('Completed', 'Completed'), ('Required', 'Required')], default='Required', max_length=50)),
                ('team', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.team')),
                ('type', models.ManyToManyField(blank=True, to='ArtyProd.service')),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('file_cv', models.FileField(blank=True, upload_to='cv/')),
                ('post', models.CharField(choices=[('Graphic Designer', 'Graphic Designer'), ('Web Designer', 'Web Designer'), ('UI/UX Designer', 'UI/UX Designer'), ('Creative Director', 'Creative Director'), ('Art Director', 'Art Director'), ('Copywriter', 'Copywriter'), ('Web Developer', 'Web Developer')], default='Graphic Designer', max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='perPhoto/')),
                ('linkedin_url', models.URLField(null=True)),
                ('fcb_url', models.URLField(null=True)),
                ('github_url', models.URLField(null=True)),
                ('eqp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.equipe')),
            ],
            options={
                'verbose_name_plural': 'Personnels',
            },
        ),
    ]
