# Generated by Django 4.1.7 on 2023-05-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0003_demande_delete_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='Type',
            field=models.CharField(choices=[('Web Design', 'Web Design'), ('conception 3D', 'Conception 3D'), ('production audiovisuelle', 'Production audiovisuelle'), ('design graphique', 'Design graphique')], default='Web Design', max_length=50),
        ),
    ]
